kind: pipeline
name: default

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: test
    image: golang:1.12
    volumes:
      - name: cache
        path: /go/pkg
    commands:
      - go mod download
      # Fail if git state is dirty after download modules
#      - git diff --quiet
      - make test
      - make build

trigger:
  event:
    - pull_request

volumes:
  - name: cache
    temp: {}

---
# ---------------------------------------------------------
kind: pipeline
type: docker
name: release

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: release
    image: golang:1.12
    commands:
      - "curl -sL https://git.io/goreleaser | bash"
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: cache
        path: /go/pkg

trigger:
  event:
    - tag

# ---------------------------------------------------------
