project_name: k2tf
builds:
  - id: k2tf
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"
archives:
  - id: k2tf
    builds:
      - k2tf
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{ .Arch }}"
snapshot:
  name_template: "{{ .Tag }}-dev-{{ .ShortCommit  }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
